import { EditorTypes } from '@wildfires-org/document-editor';

export const sampleData: EditorTypes.TemplateData = {
  id: 'refactored-doc-001',
  name: 'Refactored Sample Document.pdf',
  documentHeading: 'Refactored Project Plan',
  doc_type: 'refactored_plan',
  process: ['planning_phase'],
  ce: [],
  state: 'success',
  promptIds: {},
  type: EditorTypes.TemplateDataTypes.TEMPLATE,
  sections: [
    {
      id: 'sec_intro',
      name: 'Project Introduction',
      header_size: 'h1',
      state: 'success',
      variables: [],
      statements: [
        {
          id: 'stmt_intro_1',
          name: 'Project Name',
          description: 'Introduces the project name.',
          text: '<p>Welcome to the {projectName}.</p>',
          last_statement: false,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
        {
          id: 'stmt_intro_2',
          name: 'Project Lead',
          description: 'Identifies the project lead.',
          text: '<p>This project is led by {projectLead}.</p>',
          last_statement: false,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
        {
          id: 'stmt_intro_3',
          name: 'Main Objective',
          description: 'States the main objective of the project.',
          text: '<p>The main objective for {projectName} is to {keyGoal}.</p>',
          last_statement: true,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
      ],
      path_variable_mapping: {},
    },
    {
      id: 'sec_time',
      name: 'Project Timeline',
      header_size: 'h2',
      state: 'success',
      variables: [],
      statements: [
        {
          id: 'stmt_time_1',
          name: 'Start Date',
          description: 'Specifies the project start date.',
          text: '<p>The {projectName} is scheduled to start on {startDate}.</p>',
          last_statement: false,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
        {
          id: 'stmt_time_2',
          name: 'End Date',
          description: 'Specifies the project end date.',
          text: '<p>The planned completion date for {projectName} is {endDate}.</p>',
          last_statement: false,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
        {
          id: 'stmt_time_3',
          name: 'Schedule Management',
          description: 'Details on schedule oversight.',
          text: '<p>{projectLead} will oversee the project schedule to achieve {keyGoal} by {endDate}.</p>',
          last_statement: true,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
      ],
      path_variable_mapping: {},
    },
    {
      id: 'sec_res',
      name: 'Resources and Location',
      header_size: 'h2',
      state: 'success',
      variables: [],
      statements: [
        {
          id: 'stmt_res_1',
          name: 'Primary Site',
          description: 'Identifies the primary project site.',
          text: '<p>Key activities for {projectName} will take place at the {mainSite}.</p>',
          last_statement: false,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
        {
          id: 'stmt_res_2',
          name: 'Resource Coordination',
          description: 'Details resource coordination responsibilities.',
          text: '<p>{projectLead} will coordinate all necessary resources at the {mainSite}.</p>',
          last_statement: false,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
        {
          id: 'stmt_res_3',
          name: 'Site Readiness',
          description: 'Confirms site readiness for the project duration.',
          text: '<p>The {mainSite} is fully equipped to support {projectName} until {endDate}.</p>',
          last_statement: true,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
      ],
      path_variable_mapping: {},
    },
    {
      id: 'sec_obj',
      name: 'Key Objectives',
      header_size: 'h2',
      state: 'success',
      variables: [],
      statements: [
        {
          id: 'stmt_obj_1',
          name: 'Primary Goal',
          description: 'States the primary goal for project success.',
          text: '<p>The primary {keyGoal} must be achieved for {projectName} to be successful.</p>',
          last_statement: false,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
        {
          id: 'stmt_obj_2',
          name: 'Goal Dependency',
          description: 'Highlights dependency on achieving the key goal by the end date.',
          text: '<p>Successful completion of {projectName} by {endDate} is dependent on achieving the {keyGoal}.</p>',
          last_statement: false,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
        {
          id: 'stmt_obj_3',
          name: 'Progress Tracking',
          description: 'Details progress tracking responsibility.',
          text: '<p>{projectLead} will diligently track progress towards the {keyGoal} at the {mainSite}.</p>',
          last_statement: true,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
      ],
      path_variable_mapping: {},
    },
    {
      id: 'sec_comm',
      name: 'Stakeholder Communication Plan',
      header_size: 'h2',
      state: 'success',
      variables: [],
      statements: [
        {
          id: 'stmt_comm_1',
          name: 'Regular Updates',
          description: 'Plan for providing regular project updates.',
          text: '<p>Regular updates regarding the {projectName} will be provided to all stakeholders.</p>',
          last_statement: false,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
        {
          id: 'stmt_comm_2',
          name: 'Main Contact',
          description: 'Identifies the main point of contact.',
          text: '<p>{projectLead} will serve as the main point of contact for any queries related to {projectName}.</p>',
          last_statement: false,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
        {
          id: 'stmt_comm_3',
          name: 'Goal Communication',
          description: 'Communication strategy for the key goal.',
          text: '<p>Communication concerning the {keyGoal} and its progress will be prioritized by {projectLead}.</p>',
          last_statement: false,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
        {
          id: 'stmt_comm_4',
          name: 'Final Report',
          description: 'Plan for sharing the final project report.',
          text: '<p>A final report detailing outcomes from the {mainSite} for {projectName} will be shared after {endDate}.</p>',
          last_statement: true,
          variables: [],
          type: EditorTypes.StatementTypes.TEXT,
          actionAutoApplied: 'None',
          _triggerUpdate: false,
          typeoverMode: false,
          optionalStatement: false,
        },
      ],
      path_variable_mapping: {},
    },
  ],
  classify_prompt_id: 'refactored-classify-prompt',
  classify_image_prompt_id: 'refactored-image-classify',
  variableRegistry: {
    projectName: { name: 'projectName', initialValue: 'Alpha Project', value: '', variableHistory: [] },
    projectLead: { name: 'projectLead', initialValue: 'Jane Doe', value: '', variableHistory: [] },
    startDate: { name: 'startDate', initialValue: '2024-01-15', value: '', variableHistory: [] },
    endDate: { name: 'endDate', initialValue: '2024-10-30', value: '', variableHistory: [] },
    keyGoal: { name: 'keyGoal', initialValue: 'Launch Product', value: '', variableHistory: [] },
    mainSite: { name: 'mainSite', initialValue: 'Central Office', value: '', variableHistory: [] },
  },
}
